<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom"><title>PyVideo.org</title><link href="http://pyvideo.org/" rel="alternate"></link><link href="http://pyvideo.org/feeds/speaker_john-roach.atom.xml" rel="self"></link><id>http://pyvideo.org/</id><updated>2017-07-29T00:00:00+00:00</updated><entry><title>Integration Contract Testing and its potentials for API development and maintenance</title><link href="http://pyvideo.org/pyohio-2017/integration-contract-testing-and-its-potentials-for-api-development-and-maintenance.html" rel="alternate"></link><published>2017-07-29T00:00:00+00:00</published><updated>2017-07-29T00:00:00+00:00</updated><author><name>John Roach</name></author><id>tag:pyvideo.org,2017-07-29:pyohio-2017/integration-contract-testing-and-its-potentials-for-api-development-and-maintenance.html</id><summary type="html">&lt;h3&gt;Description&lt;/h3&gt;&lt;p&gt;You just finished a patch for your API. Your unit tests pass. You have some end to end tests that cover most of the user facing features. You merge in your code and after a smooth deployment, all hell breaks loose. The microservice that the other team was developing doesn't understand what your new patch is sending as a response! What went wrong? This is a quick talk about contract based testing.&lt;/p&gt;
</summary></entry></feed>